#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Phase 5: Script Generation & Execution (v2.9)
Generates a complete bash script for a REQUEST based on the I/O plan in TOON format.
1. 2026-02-17: Further refactored to remove duplicate code and simplify functions.
"""

import sys
import os
import json
import argparse
import subprocess
from phase_utils import invoke_coder, prepare_coder_prompt, append_result_display

# pylint: disable=useless-return

# Add project root to path for utilities
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.append(SCRIPT_DIR)


def generate_full_script(req, llm_config):
    """Generates the full bash script text from topics."""
    script_lines = ["#!/bin/bash", "# Generated by RYS Phase 5", "set -e", ""]
    final_binding = None

    for topic in req.get("topics", []):
        print(f"Coding Topic: {topic['id']} ({topic['title']})...")
        prompt = prepare_coder_prompt(topic)
        snippet = invoke_coder(SCRIPT_DIR, prompt, req.get("skill"), llm_config)

        script_lines.append(f"# --- {topic['id']}: {topic['title']} ---")
        script_lines.append(snippet)
        script_lines.append("")

        output = topic.get('output', {})
        if isinstance(output, dict) and output.get('binding'):
            final_binding = output['binding']

    append_result_display(script_lines, req.get("request_id", "UNK"), final_binding)
    return "\n".join(script_lines)


def execute_script(script_path, auto_mode):
    """Prompts for and executes the script."""
    if auto_mode:
        print("Auto-executing...")
        subprocess.run(script_path, shell=True, check=False)
    else:
        sys.stdout.write("Execute this script? [y/N]: ")
        sys.stdout.flush()
        choice = sys.stdin.readline().strip().lower()
        if choice == 'y':
            print(f"Running {script_path}...")
            subprocess.run(script_path, shell=True, check=False)
            print("Done.")
    return


def main():
    """Main entry point for Phase 5 coder execution."""
    parser = argparse.ArgumentParser(description="Phase 5: Script Generator")
    parser.add_argument("--request-json", required=True, help="Integrated Request JSON")
    parser.add_argument("--auto", action="store_true", help="Auto-execute script")
    args = parser.parse_args()

    try:
        req = json.loads(args.request_json)
    except json.JSONDecodeError:
        sys.stderr.write("Error: Invalid JSON data provided.\n")
        return

    llm_config = {
        "host": os.environ.get("RYS_LLM_HOST", "localhost"),
        "port": os.environ.get("RYS_LLM_PORT", "11434"),
        "model": os.environ.get("RYS_LLM_MODEL", "gemma3n:e4b")
    }

    print("==================================================")
    print(f">>> Phase 5: Generating Script for {req.get('request_id')}")
    print(f"Skill: {req.get('skill')}")
    print("--------------------------------------------------")

    full_script = generate_full_script(req, llm_config)

    session_uuid = os.environ.get("RYS_UUID", "default")
    cache_dir = os.environ.get("RYS_CACHE_DIR", "./tmp")
    script_fn = f".rys.{session_uuid}.{req.get('request_id')}.sh"
    script_path = os.path.abspath(os.path.join(cache_dir, script_fn))

    with open(script_path, "w", encoding="utf-8") as f_out:
        f_out.write(full_script)
    os.chmod(script_path, 0o755)

    print(f"Generated Script: {script_path}\n--------------------------------------------------")
    print(f"{full_script}\n--------------------------------------------------")

    auto_mode = args.auto or (os.environ.get("RYS_AUTO", "").lower() == "true")
    execute_script(script_path, auto_mode)
    return


if __name__ == "__main__":
    main()
